spring.application.name=backend-java

spring.datasource.url=jdbc:postgresql://localhost:5432/mybudget-db
spring.datasource.username=api
spring.datasource.password=2231M6a3rb#

api.security.token.secret=Zulu2387/*-/Alpha1445/*-/

spring.jpa.hibernate.ddl-auto=update

spring.flyway.enabled=true
spring.flyway.location=classpath:db/migration